### ISSUE TITLE
About Mix LoRA

### ISSUE THREAD

**Issue by zhhvvv** [TUDB-Labs/multi-lora-fine-tune#159]
I think this is a great job

Is there any problem with the implementation of the method? Why is the code no longer in the warehouse?

**Comment by merlintang** [comment]
thanks for mentioning this job, we are still under-testing this approach and will merge it into the main branch after it is stabled.

**Comment by mikecovlee** [comment]
thanks for supporting my work! MixLoRA currently under construction at [mikecovlee/mlora](https://github.com/mikecovlee/mlora). stay tuned if you are interested.
