### ISSUE TITLE
Train time cost report

### ISSUE THREAD

**Issue by yezhem** [TUDB-Labs/multi-lora-fine-tune#68]
this report also needs to be added to readme @merlintang @mikecovlee pls review it.
![模型执行时间比较](https://github.com/TUDB-Labs/multi-lora-fine-tune/assets/17040545/bf74935d-41d7-4cf5-b6ca-faec0e61d86d)

**Comment by merlintang** [comment]
SYNC meaning?

**Comment by merlintang** [comment]
Sure, let us put this into readme.

**Comment by yezhem** [comment]
> SYNC meaning?

Train model synchronously

**Comment by mikecovlee** [comment]
I will do it tomorrow.
