### ISSUE TITLE
example goes out of memory

### ISSUE THREAD

**Issue by ChaoGaoUCR** [TUDB-Labs/multi-lora-fine-tune#90]
Dear, Author,

Thanks for this great project, 
I hit a problem when I tried to run the example code mlora.py with float16
I use A100 with 40GB memory but it still goes out of memory.

Do you have any clue about this error?

Thanks!

**Comment by ChaoGaoUCR** [comment]
I realize it does not turn off all the requires_grad to False.
I turned them off it works now.
Thanks anyway.

**Comment by yezhem** [comment]
@ChaoGaoUCR can you show your command? train with float16 (enable checkpoint) do not need more than 40G mem.

**Comment by ChaoGaoUCR** [comment]
Yes, Here it is
![image](https://github.com/TUDB-Labs/multi-lora-fine-tune/assets/86901408/909c9afb-8505-45f9-b16a-9b331c7eb3e7)
Although I didn't mark float16 here.
I think if we set all the parameters in LLaMA requires_grad to False, we can tune it no matter what dtype, current repo may get all gradients in the whole model,
I can tune up to 128 LoRA with all parameters set to not require gradient, although I think one LoRA will use up all computation resources in A100 40GB

**Comment by yezhem** [comment]
If we use 8-bit or 4-bit, it will disable the requires_grad default, we do not test float16, maybe it's a bug, can you fix it?
Thanks

**Comment by ChaoGaoUCR** [comment]
Yeps, I fix it in my end,
I can give it a try maybe this week
